spring:
  application:
    name: apigatewayserver
server:
  port: 8765
zuul:
  sensitiveHeaders: Cookie,Set-Cookie,User-Details
  ignored-headers: Access-Control-Allow-Headers,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Max-Age
  routes:
    vendormicro:
      path: /vendor/**
      serviceId: vendormicro
    categorymicro:
      path: /category/**
      serviceId: categorymicro
    productmicro:
      path: /product/**
      serviceId: productmicro
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
